import re  
#importing RegEx

import datetime 
#importing DateTime modue

classList = ["AAKANKSHA", #classlist containing everyone's name to check with the code
"ABHINAV", 
"ADITHI", 
"AGASTYA",
"AKSHAY", 
"ARTHAV", 
"ARYAMAN", 
"AVYUKTH",
"BHARADWAJ", 
"BHASHITHA", 
"BHAVY", 
"CHARVITH",
"DILISHA", 
"DRITAN", 
"GEETHIKA", 
"GOUTHAM",
"KAVIN", 
"MANASVINI", 
"MIRZA", 
"WASI", 
"PRANAMYA", 
"RAJASHEKAR", 
"RISHMITHA", 
"RITIESHWAR",
"RUGVEDA",
"RUTHVIK", 
"SHAURYA",
"SATWIK", 
"SATYANARAYANA", 
"SHAANVI", 
"SHAHID",
"SHRADDHA", 
"SAMIUDDIN", 
"YAMEEN", 
"VANSH",
"VARSHITH", 
"VEDANTH", 
"ABHIRAM",
"VIGNAN", 
"VIKRAMADITYA", 
"ZUBIYA"]

meetPath = "./Absentees_Gen/Absentees_inspect.txt"
#file path (relative) for the G Meet code 

per = input("Please enter the subject/period: ")
#input for subject

h = datetime.datetime.now()
#gets date and time from module

dat = (str(h.day) + "/" + str(h.month) + "/" +str(h.year))
#formatiing the date and time into a string and concatenating those strings

f = open(meetPath, "r")
#opening the meet code

al = (f.read()).lower()
#reading the code

z = re.sub("[^a-zA-Z]", " ", al)
#using a RegEx (Regular Expression) to remove all the symbols, numbers and special characters
#from the code so that it is easier to parse

abs = []
#creating an array for the absentees

for i in classList:  
    #creating a for loop to sort through every name in the classList to 
    #see who is absent   

    r = re.findall(i.lower(), al)
    #using a regex to find all instances of the current name in the code
    #the output of this function is an array
    
    if (len(r) == 0): 
    #if the length of the above array is 0, it means that
    #there are no instances of the given name                  
        abs.append(i) 
        #appending that name to the absentees array 
    
print("The absentees for " + per + " class of " + dat + " are:")
#printing the messages for the list.
#this includes the period and the date                                                                

print("There are " + str(len(abs) + 1) + " absentees")         
#gets the number of absentees by checking
#the length of that array + 1
#because the array starts with 0

for i in abs:
    print(i)
#using a for loop to print out the absentees 

print("Generated by Fabsentees")       